GET http://api.eppbuyer.com/getuserdata/index.php
Authorization: T1VWc3IvRE9hTVdzTmJ2bFpSR3gvYzgvVXdmVTNiV1d1VFpHQmtKdkNkNjA0QzRaS2crblBtQTJYbGlyd2MxWGo4NEJ1emRhbEgyZ2tNTkd1TU9XNnphK2RPTjB2a3Z4am95SC91bmtoeE45OFYwSHExTkZkRjg5TU5DZlh4OUppLzhVVW9TK3VzY3pleG1SbFp4MlJyUldCK21vRmJ1dzE4ZDNZcS9ZaFJvRndGTTVYQUVaaG9leDhKYTRUandZ
Accept: application/json